modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "${issueTrackerUrl}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''${description}'''
displayURL = "${websiteUrl}"
updateJSONURL = "${forgeUpdateUrl}"
itemIcon = "minecraft:wooden_sword"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"
