name: "CI"
on: ["push", "workflow_dispatch"]

jobs:
  build:
    name: "Build for ${{ matrix.mc }}"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix: { mc: ["1.16.5", "1.18.2", "1.19.2"] }

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup Java"
        uses: actions/setup-java@v3
        with: { distribution: "temurin", java-version: "18", cache: "gradle" }

      - name: "Compile Mod for ${{ matrix.mc }}"
        run: "./gradlew build --no-daemon -Pminecraft=${{ matrix.mc }}"

      - name: "Upload Fabric Artifacts"
        uses: actions/upload-artifact@v3
        with: { name: "Fabric ${{ matrix.mc }}", path: "fabric/build/libs" }

      - name: "Upload Forge Artifacts"
        uses: actions/upload-artifact@v3
        with: { name: "Forge ${{ matrix.mc }}", path: "forge/build/libs" }
